In [1]:
import pandas as pd

In [2]:

data = pd.read_csv('F:\kutty\severeinjury1.csv',encoding='cp1252')

In [3]:

import nltk

In [4]:
from nltk.tokenize import WhitespaceTokenizer

In [7]:
from nltk.stem.snowball import SnowballStemmer
stemming = SnowballStemmer("english")

In [8]:
data["narrative"]= data["title.new"]+data["summary.new"]

In [10]:

def identify_tokens(row):
    summary_title = row["narrative"]
    tokens = nltk.word_tokenize(summary_title)
    token_words = [ w for w in tokens if w.isalpha()]
    return token_words

In [11]:
data['words']= data.apply(identify_tokens,axis=1)

In [12]:
data['words']

0      [two, workers, are, struck, by, motor, vehicle...
1      [foreman, is, fatally, crushed, when, forklift...
2      [employee, suffers, abdominal, fracture, in, f...
3      [employee, body, is, caught, in, asphalt, mach...
4      [employee, is, punctured, in, abdomen, with, n...
5      [carpenter, is, injured, in, fall, from, ceili...
6      [pipeline, worker, is, struck, and, injured, b...
7      [employee, crushes, leg, suffers, possible, fr...
8      [worker, falls, from, roof, and, breaks, arm, ...
9      [driver, hurt, when, truck, unloading, sand, o...
10     [tile, setter, sustains, injuries, in, fall, f...
11     [crane, operator, incurs, knee, injury, when, ...
12     [employee, is, killed, in, fall, from, suspens...
13     [employee, killed, in, fall, from, man, lift, ...
14     [employee, killed, in, fall, from, roof, On, m...
15     [employee, thigh, lacerated, with, abrasive, f...
16     [asphyxiated, in, rail, car, air, compressor, ...
17     [employee, killed, in, f

In [13]:
def stem_list(row):
    my_list = row['words']
    stemmed_list = [stemming.stem(word) for word in my_list]
    return(stemmed_list)

data['stemmed_words'] = data.apply(stem_list, axis=1)

In [14]:
data['stemmed_words']

0      [two, worker, are, struck, by, motor, vehicl, ...
1      [foreman, is, fatal, crush, when, forklift, ti...
2      [employe, suffer, abdomin, fractur, in, fall, ...
3      [employe, bodi, is, caught, in, asphalt, machi...
4      [employe, is, punctur, in, abdomen, with, nail...
5      [carpent, is, injur, in, fall, from, ceil, joi...
6      [pipelin, worker, is, struck, and, injur, by, ...
7      [employe, crush, leg, suffer, possibl, fractur...
8      [worker, fall, from, roof, and, break, arm, on...
9      [driver, hurt, when, truck, unload, sand, over...
10     [tile, setter, sustain, injuri, in, fall, from...
11     [crane, oper, incur, knee, injuri, when, crane...
12     [employe, is, kill, in, fall, from, suspens, s...
13     [employe, kill, in, fall, from, man, lift, on,...
14     [employe, kill, in, fall, from, roof, on, may,...
15     [employe, thigh, lacer, with, abras, from, mac...
16     [asphyxi, in, rail, car, air, compressor, fail...
17     [employe, kill, in, fall

In [15]:
from nltk.corpus import stopwords
stops = set(stopwords.words("english"))                  

def remove_stops(row):
    my_list = row['stemmed_words']
    meaningful_words = [w for w in my_list if not w in stops]
    return (meaningful_words)

data['stem_meaningful'] = data.apply(remove_stops, axis=1)

In [16]:
data['stem_meaningful']

0      [two, worker, struck, motor, vehicl, one, kill...
1      [foreman, fatal, crush, forklift, tip, approxi...
2      [employe, suffer, abdomin, fractur, fall, ladd...
3      [employe, bodi, caught, asphalt, machin, die, ...
4      [employe, punctur, abdomen, nail, approxim, se...
5      [carpent, injur, fall, ceil, joist, decemb, em...
6      [pipelin, worker, struck, injur, fall, cement,...
7      [employe, crush, leg, suffer, possibl, fractur...
8      [worker, fall, roof, break, arm, june, employe...
9      [driver, hurt, truck, unload, sand, overturn, ...
10     [tile, setter, sustain, injuri, fall, ladder, ...
11     [crane, oper, incur, knee, injuri, crane, tip,...
12     [employe, kill, fall, suspens, scaffold, octob...
13     [employe, kill, fall, man, lift, march, employ...
14     [employe, kill, fall, roof, may, employe, perf...
15     [employe, thigh, lacer, abras, machin, approxi...
16     [asphyxi, rail, car, air, compressor, fail, em...
17     [employe, kill, fall, te

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer
import math

In [18]:
data['stem_meaningful'] = ["  ".join(review) for review in data['stem_meaningful'].values]

In [19]:
data['stem_meaningful']

0      two  worker  struck  motor  vehicl  one  kill ...
1      foreman  fatal  crush  forklift  tip  approxim...
2      employe  suffer  abdomin  fractur  fall  ladde...
3      employe  bodi  caught  asphalt  machin  die  n...
4      employe  punctur  abdomen  nail  approxim  sep...
5      carpent  injur  fall  ceil  joist  decemb  emp...
6      pipelin  worker  struck  injur  fall  cement  ...
7      employe  crush  leg  suffer  possibl  fractur ...
8      worker  fall  roof  break  arm  june  employe ...
9      driver  hurt  truck  unload  sand  overturn  j...
10     tile  setter  sustain  injuri  fall  ladder  a...
11     crane  oper  incur  knee  injuri  crane  tip  ...
12     employe  kill  fall  suspens  scaffold  octob ...
13     employe  kill  fall  man  lift  march  employe...
14     employe  kill  fall  roof  may  employe  perfo...
15     employe  thigh  lacer  abras  machin  approxim...
16     asphyxi  rail  car  air  compressor  fail  emp...
17     employe  kill  fall  tel

In [20]:
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
v=TfidfVectorizer()

In [21]:
x=v.fit_transform(data['stem_meaningful'])

In [22]:

x

<1000x4285 sparse matrix of type '<type 'numpy.float64'>'
	with 45049 stored elements in Compressed Sparse Row format>

In [23]:
first_vector_v = x[0]

In [26]:
df = pd.DataFrame(first_vector_v.T.todense(),index = v.get_feature_names(),columns = ["tfidf"])
df.sort_values(by=["tfidf"],ascending=False)

tfidf
lane         0.369464
vehicl       0.318433
highway      0.212289
turn         0.204723
struck       0.186180
templar      0.177076
refus        0.167126
veer         0.160066
emerg        0.154439
fiber        0.150115
optic        0.150115
employe      0.150066
servic       0.148518
medic        0.146693
declar       0.146332
mile         0.143056
flagger      0.143056
speed        0.140165
post         0.135240
per          0.133105
privat       0.133105
worker       0.131161
limit        0.129322
underground  0.126045
mark         0.126045
special      0.120569
motor        0.120569
duti         0.114130
travel       0.111451
bruis        0.110619
...               ...
fixat        0.000000
fixtur       0.000000
fl           0.000000
flag         0.000000
flagman      0.000000
flail        0.000000
flame        0.000000
flammabl     0.000000
flang        0.000000
flash        0.000000
flashlight   0.000000
flat         0.000000
flatb        0.000000
flatiron     0.000000
fled         0.000000
flee         0.000000
fleet        0.000000
flesh        0.000000
flew         0.000000
flex         0.000000
flexibl      0.000000
fli          0.000000
flight       0.000000
flip         0.000000
float        0.000000
floor        0.000000
florida      0.000000
flour        0.000000
flourmil     0.000000
zone         0.000000

[4285 rows x 1 columns]

In [28]:
Train_X, Test_X, Train_Y, Test_Y = model_selection.train_test_split(data['summary.new'],data['Tagged2'],test_size=0.3)

NameError: name 'model_selection' is not defined

In [29]:
from sklearn.preprocessing import LabelEncoder
from collections import defaultdict
from nltk.corpus import wordnet as wn
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import model_selection, naive_bayes, svm
from sklearn.metrics import accuracy_score

In [30]:
import numpy as np

In [148]:
Train_X, Test_X, Train_Y, Test_Y = model_selection.train_test_split(data['summary.new'],data['Tagged2'],test_size=0.2)

In [149]:
Encoder = LabelEncoder()
Train_Y = Encoder.fit_transform(Train_Y)
Test_Y = Encoder.fit_transform(Test_Y)

In [150]:
Train_X_Tfidf = v.transform(Train_X)
Test_X_Tfidf = v.transform(Test_X)

In [151]:
print(v.vocabulary_)

{u'yellow': 4277, u'interchang': 1917, u'four': 1491, u'unattach': 3975, u'dynamit': 1159, u'whose': 4215, u'marcor': 2246, u'swab': 3692, u'swam': 3693, u'refinish': 2997, u'digit': 1042, u'guardrail': 1645, u'ductil': 1146, u'foul': 1488, u'appar': 163, u'disturb': 1081, u'sunstat': 3661, u'wooden': 4242, u'crotch': 888, u'nordiazepam': 2480, u'rusti': 3173, u'miller': 2332, u'scraper': 3233, u'second': 3254, u'lehigh': 2114, u'crozer': 892, u'even': 1275, u'captain': 528, u'wreck': 4260, u'lightn': 2138, u'new': 2454, u'net': 2450, u'ongo': 2543, u'elimin': 1198, u'crouch': 889, u'aquat': 183, u'ravenel': 2939, u'men': 2294, u'met': 2302, u'osha': 2563, u'mep': 2298, u'cardboard': 533, u'interpret': 1923, u'taper': 3738, u'postop': 2788, u'dri': 1126, u'permit': 2689, u'climber': 683, u'counti': 856, u'golden': 1590, u'nineti': 2464, u'ground': 1638, u'brought': 449, u'sterl': 3573, u'unit': 4016, u'landfil': 2063, u'unanchor': 3972, u'halogen': 1663, u'call': 509, u'recommend': 297

In [38]:
print(Train_X_Tfidf)

  (0, 4227)	0.30072138056945685
  (0, 4156)	0.3068691783315784
  (0, 3958)	0.16263343693774063
  (0, 3804)	0.13809139021688113
  (0, 3707)	0.15726576640118428
  (0, 3614)	0.08176063009639202
  (0, 3552)	0.1285783174487825
  (0, 3349)	0.09243121522134827
  (0, 3102)	0.09413324269688933
  (0, 2783)	0.1468301619021715
  (0, 2741)	0.18125338396271334
  (0, 2542)	0.16381993098358677
  (0, 2109)	0.08871540807601551
  (0, 1521)	0.24177044194890168
  (0, 1491)	0.12073604366529195
  (0, 1442)	0.09524438489066933
  (0, 1414)	0.13725157532113225
  (0, 1373)	0.06033369242431758
  (0, 1372)	0.08439819719360095
  (0, 1166)	0.1781719052379827
  (0, 987)	0.1622496206050655
  (0, 878)	0.1105760385388721
  (0, 691)	0.6326340917464495
  (0, 511)	0.11975623972507164
  (0, 39)	0.13725157532113225
  :	:
  (799, 2188)	0.1100168500486541
  (799, 2111)	0.06604461308816252
  (799, 2050)	0.06779014038733765
  (799, 1848)	0.1100168500486541
  (799, 1765)	0.08434180564455929
  (799, 1705)	0.1100168500486541
  (799

In [39]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(Train_X,Train_Y)

ValueError: could not convert string to float: At approximately 3:45 p.m. on january 26 2012 a crew of five employees was working to demolish a storage closet measured approximately 9 ft. by 4 ft. by 12 ft. which is located on the third floor of a

In [41]:
SVM = svm.SVC(C=1.0, kernel='linear', degree=3, gamma='auto')
SVM.fit(Train_X_Tfidf,Train_Y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [42]:
predictions_SVM = SVM.predict(Test_X_Tfidf)

In [44]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(Test_Y,predictions_SVM))
print(classification_report(Test_Y,predictions_SVM))
print(accuracy_score(Test_Y, predictions_SVM))

[[ 7  2  0  0  0  0  0  0  0  2  0]
 [ 1 21  0  0  0 13  0  2  0  2  1]
 [ 0  1 15  0  0  0  0  1  0  1  0]
 [ 0  1  0  2  0  0  0  2  0  3  0]
 [ 0  1  0  0  2  1  0  0  0  1  0]
 [ 0 11  1  0  0 35  0  0  0  1  0]
 [ 0  3  0  0  0  1  6  0  0  4  0]
 [ 0  2  1  0  0  1  0  1  0  1  0]
 [ 1  1  0  0  0  1  0  0  1  2  1]
 [ 2  7  1  0  0  4  1  0  0 16  1]
 [ 0  5  0  0  0  0  0  0  0  0  6]]
              precision    recall  f1-score   support

           0       0.64      0.64      0.64        11
           1       0.38      0.53      0.44        40
           2       0.83      0.83      0.83        18
           3       1.00      0.25      0.40         8
           4       1.00      0.40      0.57         5
           5       0.62      0.73      0.67        48
           6       0.86      0.43      0.57        14
           7       0.17      0.17      0.17         6
           8       1.00      0.14      0.25         7
           9       0.48      0.50      0.49        32
        

In [45]:
Naive = naive_bayes.MultinomialNB()
Naive.fit(Train_X_Tfidf,Train_Y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [46]:
predictions_NB = Naive.predict(Test_X_Tfidf)

In [47]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(Test_Y,predictions_NB))
print(classification_report(Test_Y,predictions_NB))
print(accuracy_score(Test_Y, predictions_NB))

[[ 0  8  0  0  0  3  0  0  0  0  0]
 [ 0 16  0  0  0 24  0  0  0  0  0]
 [ 0  1 10  0  0  7  0  0  0  0  0]
 [ 0  2  0  0  0  6  0  0  0  0  0]
 [ 0  1  0  0  0  4  0  0  0  0  0]
 [ 0  3  0  0  0 45  0  0  0  0  0]
 [ 0  4  0  0  0 10  0  0  0  0  0]
 [ 0  1  0  0  0  5  0  0  0  0  0]
 [ 0  5  0  0  0  2  0  0  0  0  0]
 [ 0 11  0  0  0 16  0  0  0  5  0]
 [ 0 11  0  0  0  0  0  0  0  0  0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        11
           1       0.25      0.40      0.31        40
           2       1.00      0.56      0.71        18
           3       0.00      0.00      0.00         8
           4       0.00      0.00      0.00         5
           5       0.37      0.94      0.53        48
           6       0.00      0.00      0.00        14
           7       0.00      0.00      0.00         6
           8       0.00      0.00      0.00         7
           9       1.00      0.16      0.27        32
        

C:\Users\veera\Anaconda2\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [48]:
from sklearn.tree import DecisionTreeClassifier

In [50]:
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(Train_X_Tfidf,Train_Y)

#Predict the response for test dataset
y_pred = clf.predict((Test_X_Tfidf))

In [51]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(Test_Y,y_pred))
print(classification_report(Test_Y,y_pred))
print(accuracy_score(Test_Y, y_pred))

[[10  0  1  0  0  0  0  0  0  0  0]
 [ 2 15  1  0  0 14  0  2  2  2  2]
 [ 0  4 13  0  0  0  0  0  0  1  0]
 [ 0  1  1  2  0  0  0  2  0  2  0]
 [ 0  0  2  0  0  1  0  0  0  1  1]
 [ 0 14  1  0  0 29  0  0  2  0  2]
 [ 1  2  2  1  0  0  4  2  0  2  0]
 [ 0  1  1  0  0  0  1  3  0  0  0]
 [ 1  4  0  0  0  0  0  0  2  0  0]
 [ 3  1  1  0  0  2  1  1  1 20  2]
 [ 0  3  0  0  0  1  0  1  1  2  3]]
              precision    recall  f1-score   support

           0       0.59      0.91      0.71        11
           1       0.33      0.38      0.35        40
           2       0.57      0.72      0.63        18
           3       0.67      0.25      0.36         8
           4       0.00      0.00      0.00         5
           5       0.62      0.60      0.61        48
           6       0.67      0.29      0.40        14
           7       0.27      0.50      0.35         6
           8       0.25      0.29      0.27         7
           9       0.67      0.62      0.65        32
        

In [106]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=15)

In [107]:
classifier.fit(Train_X_Tfidf,Train_Y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=15, p=2,
           weights='uniform')

In [108]:
y_pred = classifier.predict((Test_X_Tfidf))

In [109]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(Test_Y,y_pred))
print(classification_report(Test_Y,y_pred))
print(accuracy_score(Test_Y, y_pred))

[[ 8  2  1  0  0  0  0  0  0  0  0]
 [ 0 31  0  0  0  8  0  0  0  0  1]
 [ 1  5 10  0  0  2  0  0  0  0  0]
 [ 0  3  1  2  0  0  0  0  0  1  1]
 [ 0  4  0  0  0  1  0  0  0  0  0]
 [ 0 15  1  0  0 31  0  0  0  0  1]
 [ 0  4  2  0  0  3  5  0  0  0  0]
 [ 0  3  0  0  0  2  0  0  0  1  0]
 [ 0  5  0  0  0  1  0  0  0  0  1]
 [ 1 15  0  0  0  8  0  0  0  7  1]
 [ 0  5  0  0  0  0  0  0  0  0  6]]
              precision    recall  f1-score   support

           0       0.80      0.73      0.76        11
           1       0.34      0.78      0.47        40
           2       0.67      0.56      0.61        18
           3       1.00      0.25      0.40         8
           4       0.00      0.00      0.00         5
           5       0.55      0.65      0.60        48
           6       1.00      0.36      0.53        14
           7       0.00      0.00      0.00         6
           8       0.00      0.00      0.00         7
           9       0.78      0.22      0.34        32
        

In [142]:
from sklearn.linear_model import LogisticRegression

In [160]:
clf = LogisticRegression()
clf.fit(Train_X_Tfidf,Train_Y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [152]:
y_pred = clf.predict(Train_X_Tfidf[0].reshape(1,-1))
y_pred = clf.predict(Train_X_Tfidf[0:800].reshape(1,-1))

ValueError: X has 3428000 features per sample; expecting 4285

In [145]:
y_pred = clf.predict(Train_X_Tfidf)

In [129]:
Test_Y.shape

(200L,)

In [170]:
X_data = np.array(data['summary.new'])
Y_data = np.array(data['Tagged2'])

In [172]:
Train_X, Test_X, Train_Y, Test_Y = model_selection.train_test_split(X_data,Y_data,test_size=0.2)

In [173]:
Encoder = LabelEncoder()
Train_Y = Encoder.fit_transform(Train_Y)
Test_Y = Encoder.fit_transform(Test_Y)

In [174]:
Train_X_Tfidf = v.transform(Train_X)
Test_X_Tfidf = v.transform(Test_X)

In [175]:
from sklearn.linear_model import LogisticRegression

In [176]:
clf = LogisticRegression()
clf.fit(Train_X_Tfidf,Train_Y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [163]:
y_pred = clf.predict(Train_X_Tfidf)

In [164]:
y_pred = clf.predict(Train_X_Tfidf)

In [165]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(Test_Y,y_pred))
print(classification_report(Test_Y,y_pred))
print(accuracy_score(Test_Y, y_pred))

ValueError: Found input variables with inconsistent numbers of samples: [200, 800]

In [177]:
print(Test_Y.shape)

(200L,)


In [178]:
print(Test_Y.ndim)

1


In [179]:
print(y_pred.shape)

(800L,)


In [180]:
print(y_pred.ndim)

1


In [181]:
Test_Y

array([ 1,  2,  8,  9,  6,  1,  0,  5,  9,  9,  5,  1, 10,  9,  1,  9,  2,
        9, 10,  8,  1,  1,  6,  1,  2,  8,  5, 10,  9,  1,  9,  8,  3,  9,
        1,  9,  5,  1,  5,  8,  5,  5,  1,  0,  1,  5,  5,  0,  1,  2,  1,
        5,  5,  5,  9,  5,  1,  7,  5,  4,  9,  1,  2,  4,  0,  5,  1,  9,
        2,  2,  5,  8, 10,  0,  1,  5,  2,  1,  7,  4,  2,  1,  5,  9,  1,
        2,  5,  9,  5,  1,  7,  2,  9,  5,  1,  8,  1,  0,  5,  0,  2,  5,
        0, 10,  3,  9,  1,  1,  5,  5,  2,  9,  6, 10,  6, 10,  7,  1, 10,
        2,  1,  0,  1,  0,  1,  9,  9,  5,  9,  1,  5, 10,  1,  6,  9,  5,
        8,  5,  9,  5,  1,  3,  1,  1,  5,  2, 10,  5,  5,  5,  2,  5,  5,
        1,  6,  0,  9,  5,  5,  5,  5,  0,  0,  5,  5,  2,  9,  5,  1,  2,
        1,  0,  1,  2,  2,  8,  6,  1,  6,  1,  0,  0,  1,  6,  5,  1,  2,
        1,  3,  1,  0,  8,  9,  8,  2,  1, 10,  9,  7,  7])

In [191]:
N = 600
W=np.pad(Test_Y, (0,N),'constant')

In [192]:
print(W.shape)

(800L,)


In [193]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(W,y_pred))
print(classification_report(W,y_pred))
print(accuracy_score(W, y_pred))

[[ 28 170  70  12   1 185  16   3   5  93  34]
 [  0  12   3   2   0  14   1   2   0   9   3]
 [  1   3   3   0   0  13   0   0   0   1   1]
 [  0   1   1   0   0   2   0   0   0   0   0]
 [  0   1   1   0   0   0   0   0   0   1   0]
 [  1  17   2   1   0   8   3   2   2   5   3]
 [  0   2   0   0   0   4   0   0   1   2   0]
 [  1   1   3   0   0   1   0   0   0   0   0]
 [  1   2   1   0   0   4   0   0   0   2   1]
 [  2   6   2   1   0  10   2   0   0   2   2]
 [  1   2   1   0   0   5   0   2   0   0   0]]
              precision    recall  f1-score   support

           0       0.80      0.05      0.09       617
           1       0.06      0.26      0.09        46
           2       0.03      0.14      0.06        22
           3       0.00      0.00      0.00         4
           4       0.00      0.00      0.00         3
           5       0.03      0.18      0.06        44
           6       0.00      0.00      0.00         9
           7       0.00      0.00      0.00      

In [194]:
import seaborn as sn

In [195]:
confusion_matrix = pd.crosstab(Test_Y,y_pred)

ValueError: arrays must all be same length